Doxygen CI: Warnings as Error (#3560)
Make sure that no Doxygen warnings get in, as we do in other CI runs
already.

Depends on https://github.com/AMReX-Codes/amrex/pull/3061

---------

Co-authored-by: Edoardo Zoni <ezoni@lbl.gov>
Co-authored-by: Edoardo Zoni <59625522+EZoni@users.noreply.github.com>
Co-authored-by: David Grote <dpgrote@lbl.gov>

diff --git a/.github/workflows/source/doxygen b/.github/workflows/source/doxygen
--- a/.github/workflows/source/doxygen
+++ b/.github/workflows/source/doxygen
@@ -1,15 +1,27 @@
 #!/usr/bin/env bash
 #
-# Copyright 2020 Axel Huebl
+# Copyright 2020-2023 The WarpX Community
 #
 # License: BSD-3-Clause-LBNL
-
-# search recursive inside a folder if a file contains tabs
-#
-# @result 0 if no files are found, else 1
-#
+# Authors: Axel Huebl
 
 set -eu -o pipefail
 
 cd Docs
+
+curl -L -o amrex-doxygen-web.tag.xml \
+  https://amrex-codes.github.io/amrex/docs_xml/doxygen/amrex-doxygen-web.tag.xml
+
+curl -L -o openpmd-api-doxygen-web.tag.xml \
+  https://openpmd-api.readthedocs.io/en/latest/_static/doxyhtml/openpmd-api-doxygen-web.tag.xml
+
+# Treat all warnings as errors
+if ! grep -q "WARN_AS_ERROR = YES" Doxyfile; then
+    # Add line with the comment
+    echo "" >> Doxyfile
+    echo "# Overwrite value of WARN_AS_ERROR" >> Doxyfile
+    echo "WARN_AS_ERROR = YES" >> Doxyfile
+fi
+
+# Run doxygen
 doxygen
